---
- hosts: instance
  become: true
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: latest

    - name: Create the index file
      copy:
        dest: /var/www/html/index.html
        content: This is first server


    - name: Restart the service
      service:
         name: httpd 
         state: restarted